export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS';
export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_PRODUCT_REVIEWS_SUCCESS ';
export const GET_PRODUCT_REVIEWS_FAIL = 'GET_PRODUCT_REVIEWS_FAIL';

export const SUBMIT_PRODUCT_REVIEW = 'SUBMIT_PRODUCT_REVIEW';
export const SUBMIT_PRODUCT_REVIEW_SUCCESS = 'SUBMIT_PRODUCT_REVIEW_SUCCESS';
export const SUBMIT_PRODUCT_REVIEW_FAIL = 'SUBMIT_PRODUCT_REVIEW_FAIL';

