export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';


export const ADD_NEW_USER = 'ADD_NEW_USER';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
export const ADD_NEW_USER_FAIL = 'ADD_NEW_USER_FAIL';


export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = ' DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = ' DELETE_USER_FAIL';
