export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const ADD_TO_CART_DUPLICATE = 'ADD_TO_CART_DUPLICATE';

export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_FAIL = 'GET_CART_ITEMS_FAIL';

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAIL = 'REMOVE_CART_ITEM_FAIL';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';

export const GET_CART_SIZE = 'GET_CART_SIZE';